apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    uid: mariadb
    access: proxy
    url: mariadb:3306
    user: crypto
    database: crypto
    editable: false
    secureJsonData:
      password: crypto
